# Postgres version 0.17
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'

development:
  adapter: postgresql
  encode: unicode
  host: ec2-54-204-35-114.compute-1.amazonaws.com
  database: d58u6urdvtkreb
  port: 5432
  username: jqmeesjynxwmrx
  password: MSblVa3BrLiEl1qEQd_onagHQM
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encode: unicode
  host: localhost
  database: cookiebutter
  port: 5432
  username: cookie
  password: butter
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encode: unicode
  host: ec2-54-197-241-64.compute-1.amazonaws.com
  database: deo43j9h1ltjqr
  port: 5432
  username: fmgpgmpmkqnkta
  password: Go2XqJMeCkG8bAuLPgvv5VzeMP
  pool: 5
  timeout: 5000