# Postgres version 0.17
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'

development:
  adapter: postgresql
  encode: unicode
  host: ec2-54-235-78-155.compute-1.amazonaws.com
  database: d8149tmflo5qjh
  port: 5432
  username: crpuamfqmjqrfd
  password: _tTTmVeHIynTOtW4JWgkGax6IW
  pool: 5
  timeout: 5000

linkedin:
  adapter: postgresql
  encode: unicode
  host: ec2-23-23-177-33.compute-1.amazonaws.com
  database: d31mq2fgobhnk
  port: 5432
  username: jslsezphpapxtd
  password: 06uNad4DWGmDsymTlP8aRw88zY
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encode: unicode
  host: ec2-54-204-47-58.compute-1.amazonaws.com
  database: d3bav596gcla5n
  port: 5432
  username: glmdhwtywtuqop
  password: BXJqJGjC1qS-bGCVPvovWmVmDJ
  pool: 5
  timeout: 5000
